### ISSUE TITLE
chapter17 event word

### ISSUE THREAD

**Issue by liangpeili** [bpesquet/thejsway#108]
In [this](https://github.com/bpesquet/thejsway/blob/master/manuscript/chapter17.md#submitting-a-form)  part of chapter 17.
>You can event cancel the request to the server by calling the preventDefault() method on the Event object associated to the event.

Is this 'event' here should be replaced by 'even' instead?

**Comment by mtrivera** [comment]
I think it should be:

You can cancel the event request to the server by calling the preventDefault() method on the Event object associated to the event.

**Comment by mtrivera** [comment]
This has been fixed in #111 
This can be closed.
