### ISSUE TITLE
Indonesian version

### ISSUE THREAD

**Issue by adisetiawan** [bpesquet/thejsway#113]
Hello,
any possibilities whether I can translate it to Indonesian ? thanks

**Comment by bpesquet** [comment]
Sorry for answering late, I was on vacation.

Sure, thanks for your help! The translation process is just starting up, I invited you to join the Indonesian translation team. Please read the [translation guidelines](https://github.com/bpesquet/thejsway/blob/master/CONTRIBUTING.md#translation-guidelines) and feel free to ask if you have any question.

Good luck and thanks again!
