### ISSUE TITLE
Is this book "The JavaScript Way" is available for free ?

### ISSUE THREAD

**Issue by jitendra3109** [bpesquet/thejsway#114]
But I see here need to [pay ->](https://leanpub.com/thejsway)
Also, I see there some content in repo and also  read your article on medium but still not clear.
So would you like clear.

**Comment by bpesquet** [comment]
Hi, the book sources are free to read online here on GitHub, but the ebook version (PDF/EPUB/MOBI formats) is for sale on Leanpub. There, you can also purchase the source code for all exercises and projects.

**Comment by jitendra3109** [comment]
free to read online here on GitHub -> Is that all the content ?
What exactly diff?

**Comment by bpesquet** [comment]
All content is free to read online, except source code for exercises and projects. The paid ebook version offers a better reading experience.

**Comment by jitendra3109** [comment]
+1
