### ISSUE TITLE
Use the right typography trouhout the book

### ISSUE THREAD

**Issue by bigfatbird** [bpesquet/thejsway#121]
https://webdesignledger.com/common-typography-mistakes-apostrophes-versus-quotation-marks/

Maybe not high priority but i wanted to point this out. The book has some quirks regarding typography.
We could start to get this right.

**Comment by bpesquet** [comment]
Sure! Thanks for the link, I'll investigate this issue.

**Comment by bpesquet** [comment]
Hi @bigfatbird,
Could you point me to a example of quotation mark misuse in the book? i'm not an English native and this issue is quite confusing. Thanks in advance.

**Comment by bigfatbird** [comment]
Well I’m not a native speaker, too. But have a look about your use of the apostrophe, for example when using the word don't vs. don’t. You might see the ’ is a bit more tilted than the '. I might be wrong here, but I’ve seen it in the book text. Also for quotes there is a difference between the symbol for feet and the double quotation marks. https://en.wikipedia.org/wiki/Quotation_mark

Have a look at the provided links. :)

**Comment by rwxrob** [comment]
Speaking of suggested edits, what do you suggest? This book has become my first recommendation for beginners (out of the dozens I have read and reviewed). It is the single best JavaScript book I have ever read. You have done an amazing job despite the language barrier. You have a clear, consistent, understandable voice in your writing that is far too undervalued today.

However, there are a number of tiny editing corrections and perhaps grammar adjustments that I would suggest. I'm a native English speaker (who learned French and Russian) who obsesses about good writing and communication who also has made a living mentoring people for the last eight years. That's not so much a flex as a statement of credentials. I desperately want this book to become the top beginner JavaScript recommendation and want to help any way I can.

Would PDF annotations work? Evince (the default PDF reader on PopOS) allows the addition of annotations. These would be suggestions more than commitments as pull requests.

Another way would be simply to submit a pull request, but I wonder how big the scope of the pull request should be. I can submit them one chapter at a time, or perhaps for the whole book.

**Comment by bpesquet** [comment]
Hi Rob,

First of all, sorry for answering so late and many thanks for your kind words.

I also think that this book has its place in the JS education landscape. However, I failed at promoting it properly. Without a prominent social media profile, self-marketing a book is harder than writing it, which says a lot. Your message encourages me to try harder :)

I would very much welcome any additions or corrections by any means you would choose.

**Comment by bpesquet** [comment]
Commits f7142ed41 and 37b0e30b fix many of these mistakes.
Don't hesitate to pinpoint other typography issues.
Closing this issue for now.
