### ISSUE TITLE
chapter 22 > weather

### ISSUE THREAD

**Issue by AlexOros** [bpesquet/thejsway#131]
Hello, on the Key-based authentication chapter, the API access key is not free anymore. I made an account and when I went to the [weather API for developers](https://www.wunderground.com/weather/api/) sublink found this:

> To improve our services and enhance our relationship with our users, **we will no longer provide free weather API keys as part of our program**. If you have been directed to download our Weather Underground free API key by a third party provider, please contact your vendor for resolution.

P.s thank you for the great book 👍

**Comment by bpesquet** [comment]
You're right, I will update this chapter accordingly.

P.S. You're welcome ;)

**Comment by fleuronvilik** [comment]
Hello @bpesquet! Both me and and @AlexOros are facing the same problem. No problem with the [Punk API](https://punkapi.com).
Thanks for the book.

**Comment by bpesquet** [comment]
At long last, 8934bd05369540b8329f93a6ece7f63bade374c8 fixes this :)
