### ISSUE TITLE
Contributing Additional Exercises

### ISSUE THREAD

**Issue by rwxrob** [bpesquet/thejsway#138]
I have a number of exercises that I have been using for years that I would also like to integrate or reference at appropriate points in the book. What is the best way to do this? I see two ways:

1. Add them to the book itself
2. Add them as separate repos and refer to them in book

Given the growing popularity of the book, I propose exercise contributions be kept in their own repos, maintained by their own contributors, and that some way to reference these additional exercises be added to the book itself in order to inform readers that they exist, perhaps in a special *Forward*. This way the book itself will not be overwhelmed with exercises and readers can identify their preferred set of exercises based on their interests and needs.

**Comment by bpesquet** [comment]
Hi again Rob,

Keeping exercises in dedicated repos may be the best solution. Feel free to add links to them via a PR.

A possibility is to create these repos in the <https://github.com/thejsway> organization, or in any place you'll find more appropriate.

Thanks in advance!

**Comment by bpesquet** [comment]
Hi Rob,
i'm updating the book and cleaning up the issues. Feel free to reach out anytime you like in the future. Thanks for your help.
