### ISSUE TITLE
broken link / Chapter 17 

### ISSUE THREAD

**Issue by roxerto** [bpesquet/thejsway#144]
the following text contains a broken link:
For a more general recap on forms, check out this [course chapter]( https://www.ediciones-eni.com/open/mediabook.aspx?idR=f638649491df5468de04de371669a82c) on OpenClassrooms.

By the way, what should I do with these links in the spanish version? With sources from the MDN or wikipedia I just replace them  with their spanish equivalent, but with some other souces there is no spanish version. In a previous chapter I chose another source from the wen on the same topic, but I don't know if this is correct or allowed.

**Comment by bpesquet** [comment]
Hi, good question.
The choice is up to you. Maybe the best thing is to find another reliable source on the same topic, like you already did.
Thanks again for all your work!
