### ISSUE TITLE
function instead of functions -> Chapter 18

### ISSUE THREAD

**Issue by roxerto** [bpesquet/thejsway#149]
At the end of the "Stop an animation" section, there is this paragraph:

The `cancelAnimationFrame()` functions stops the animation and takes the ID of the animation set by a prior call to `requestAnimationFrame()`.

In the previous code to this paragraph the function `cancelAnimationFrame()` is only used once. So, I think the word *function* must be singular and not plural! Seems like just a typo!

**Comment by bpesquet** [comment]
Good catch, thanks once again!
