### ISSUE TITLE
leave vs let -> Chapter 18

### ISSUE THREAD

**Issue by roxerto** [bpesquet/thejsway#150]
In the "An alternative: CSS animations" section, there is a comment in one of the lines of code that says:

/* Let the block in its final position */

First of all, I should note I'm not a native English speaker. But, I think the word you meant instead of *let* it is "leave". Let as long as I know, gives the sense (among others) of allowing or making something to happen, and leave is it more similar to putting something in somewhere.

By the way, is it ok to open an issue for each think I notice as  I'm advancing in the translation, or do you prefer I collect all of them and open only one issue in each chapter. I do no not want to become anoying!

**Comment by bpesquet** [comment]
Hi,

You're not annoying *at all*. Your proofreading is very important to improve the book's quality!

Regarding the "one issue per problem" question, do as what's simpler for you, I'll adapt.
