### ISSUE TITLE
Chapter 20 tinyIssues

### ISSUE THREAD

**Issue by roxerto** [bpesquet/thejsway#154]
1
In the "Anatomy of an HTTP request" section there is this line:

This HTTP request comes under the form as a multi-line piece of text similar to the following one.

The expression "under the form as" souns a bit odd, I actually haven't heard it before. I asked a few native english speakers and they say the most common one is "in the form of", and if you want to use the words "under the form", it could be "under the form of". 

a)
This HTTP request comes in the form of a multi-line piece of text similar to the following one.

b)
This HTTP request comes under the form of a multi-line piece of text similar to the following one.

2
In the same section mentioned above, I found this sentence:

They are many other possible header fields.

I think the correct expression is "There are many..."

3
In the "Adressing a resource with a URL" section, there is this sentence before a list of elements. 

This address can be split into several subparts

I think a colon or full stop sign is missing at the end of the line. 

4
In the second last paragraph of the chapter there is this sentence:

Name are always within double quotes `""`.

I think the word "name" should be plural, due to the plural form of the verb to be (are).

**Comment by bpesquet** [comment]
Thanks, also fixed in #155.
