### ISSUE TITLE
The JavaScript Way Translation in Persian 

### ISSUE THREAD

**Issue by ghost** [bpesquet/thejsway#156]
Hi, 
@bpesquet I want to contribute and start the Persian translation of this book. Can I do that? Please let me know
Thank you.

**Comment by bpesquet** [comment]
Hi,
Sorry for answering so late, I just came back from some holidays.
It's a great idea! I'll set up the repo and give you write access ASAP.
Thanks in advance.

**Comment by ghost** [comment]
This is great. Thank you

**Comment by ghost** [comment]
@bpesquet Please let me know if I can contribute to the translation of The JavaScript Way book, Thank you.

**Comment by ghost** [comment]
I close this. Thank you for the reply.

**Comment by bpesquet** [comment]
Hi,
Sorry for the long delay. I just created the [persian repo](https://github.com/thejsway/thejsway_per) and invited you into the translation team.
Feel free to ask any question, I'll promise to answer them more quickly ;)
Thanks in advance!

**Comment by ghost** [comment]
Thank you so much. I start the Persian translation right away. This is awesome!

**Comment by ghost** [comment]
@bpesquet I translated three sections so far. this is the Readme 
https://github.com/najmiehsa/thejsway_per/blob/main/README.md
there are two sentences missing here and those are:

As a DRM-free Kindle or paperback book on [Amazon](https://www.amazon.com/dp/2956444611?ref_=pe_3052080_397514860).
As an interactive online course on [Educative](https://www.educative.io/courses/the-complete-javascript-course-build-a-real-world-app-from-scratch).

I am trying to figure out the markdown for this since the Persian language is from right to left and needs some configurations.
 
I am unsure why I can not submit a PR to the Persian repo. Something else I am trying to figure out is the ESlint for the Persian repo.

**Comment by bpesquet** [comment]
Hi,
Rather than forking it, you should be able to clone the [persian repo](https://github.com/thejsway/thejsway_per) then push to it directly.
Let me know if you still have difficulties.
Thanks in advance for your work!

**Comment by ghost** [comment]
@bpesquet hi,
Thanks for the tip.
I didn't know that changing my fork would cause many commits to this [PR](https://github.com/thejsway/thejsway_per/pull/1)
I re-adjusted it in the [second one](https://github.com/thejsway/thejsway_per/pull/2)

**Comment by ghost** [comment]
@bpesquet I merge the PRs to see the progress. I modify any changes that are required based on them. 
Please tell me If I need to follow a review and then merge workflow.

**Comment by ghost** [comment]
Just an update: I am facing an slow net connection and I can not submit PRs here.
I''ve done couple more chapters and I'll soon update the Persian Repo.

**Comment by ghost** [comment]
@bpesquet I am sorry please remove the Persian repository. 
I want to delete my GitHub account. 
Regards.
