### ISSUE TITLE
Translate to brazilian portuguese

### ISSUE THREAD

**Issue by vdeverena** [bpesquet/thejsway#159]
Hey @bpesquet I would like to translate the book to PTBR.

**Comment by bpesquet** [comment]
Hi, great idea!
I have created a [specific repo](https://github.com/thejsway/thejsway_pt) and invited you to a team with writing rights on it.
Thanks in advance for your help!

**Comment by vdeverena** [comment]
Thanks! I'm happy to contribute.

**Comment by vdeverena** [comment]
Hey @bpesquet! I don't have push access to the repo. Do I have to create all files directly on GitHub?
