### ISSUE TITLE
Chapter 16 > Reacting to common events > Key presses. Typo in the second paragraph

### ISSUE THREAD

**Issue by SrZorro** [bpesquet/thejsway#20]
[This paragraph](https://github.com/bpesquet/thejsway/blob/master/manuscript/chapter16.md#key-presses) has a typo where "Yhe" should be "The"

> The following example shows in the console the character associated to a pressed key. **Yhe** character info is given by the charCode property of the Event object associated to the event. This property returns a numerical value (called Unicode value) that can be translated to a string value by the String.FromCharCode() method.

**Comment by maxshaw** [comment]
Chapter 04: **Yry**

Coding time!
=========
**Yry** to code each exercise twice, once with a while loop and the other with a for, to see for yourself which one is the most appropriate.
