### ISSUE TITLE
Chapter 18 > Animate page elements 

### ISSUE THREAD

**Issue by helsus** [bpesquet/thejsway#23]
You shouldn't use 'left' for moving elements, because it will cause relayout of whole page on every frame. Use 'transform: translate'

**Comment by bpesquet** [comment]
You are certainly right, I'm no CSS guru. A PR would be welcome ;)

**Comment by MOSHE38** [comment]
Please I like to know if this issue has been fixed @bpesquet 
Thanks

**Comment by bpesquet** [comment]
Since CSS animations are outside the scope of this JS-centered book, I simplified this chapter and removed this example to avoid promoting suboptimal techniques.
