### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by neo112358** [bpesquet/thejsway#26]
Can I translated this fantastic book into chinese on github?

**Comment by bpesquet** [comment]
Yes, sure!

Let me figure out how to organize this. I'll get back to you in a few days.

**Comment by nrstmss** [comment]
r

**Comment by ttop5** [comment]
Can I join you? :bowtie:

**Comment by bpesquet** [comment]
@ttop5 Sure! i'll give more news about the translation process before the end of the week.

**Comment by liangpeili** [comment]
Please count me in on this project.

**Comment by ttop5** [comment]
@bpesquet OK, thank you!

**Comment by itsnotvalid** [comment]
Comment to follow.

**Comment by bpesquet** [comment]
Hi all, sorry for the lack of update on this topic.

The translation process is just starting up. Please read the [guidelines](https://github.com/bpesquet/thejsway/blob/master/CONTRIBUTING.md#translation-guidelines) and follow the instructions if you want to help with this effort.

Thanks in advance!
