### ISSUE TITLE
intro01.md - appendix link issue

### ISSUE THREAD

**Issue by uberrobert** [bpesquet/thejsway#28]
https://github.com/bpesquet/thejsway/blob/master/manuscript/intro01.md
"Refer to the appendix for details on both"

The appendix link doesn't appear to go to any appendix.
Maybe I'm missing something.

**Comment by bpesquet** [comment]
Leanpub and GitHub are mutually incompatible on this. I have removed all crosslinks for now and will work on a solution.

**Comment by uberrobert** [comment]
Thanks
