### ISSUE TITLE
Machine language != Assembly language

### ISSUE THREAD

**Issue by msegado** [bpesquet/thejsway#38]
First: thanks for making this book available!

I just came across the following [in intro02.md](https://github.com/bpesquet/thejsway/blob/51dcffe71cf2978a03ff7ed90ebcce4d7ac5a0af/manuscript/intro02.md#closest-to-the-hardware-assembly-language):
> The only programming language directly understandable by a computer is **machine language**, also known as assembly language.

I believe this is incorrect... Machine language and assembly are actually two distinct things. Machine language usually refers to the actual binary format understood by the processor, that is, the set of ones and zeros that you feed into it to make it do stuff. Assembly, on the other hand, is a (barely) human-readable language that translates *nearly* one-to-one into machine code... but not quite. One substantial difference of assembly is the ability to use abstract labels for jump locations and have the jump address offsets computed automatically (instead of having to compute them manually, and then having to change them all any time you add/remove any code between them): https://stackoverflow.com/a/3551967 . Also, in some cases assembly language include *pseudo-ops*, which don't always translate to the same machine instruction or which translate to multiple machine instructions: https://stackoverflow.com/a/40784745 .

Hope that helps!

**Comment by bpesquet** [comment]
Enlightening, thanks!
