### ISSUE TITLE
Pull request for chapter on arrays - a sample of suggestions 

### ISSUE THREAD

**Issue by theo-armour** [bpesquet/thejsway#5]
Salut @bpesquet 

Thank you for creating this simple, readable, modern introduction to my favorite language.

I really enjoy that you are living in the present/future and ignoring all the outdated stuff.

Separately, I am making a pull request for some suggestions for your chapter on Arrays.

If you like this effort, then I can keep on working on the other chapters.

Theo

**Comment by bpesquet** [comment]
Hi Theo,

Thanks for your kind words and your support. I merged your PR and made a few very minor fixes.

Any further contributions would of course be greatly appreciated.

Feel free to spread the word around you about the book. For a new project like this, more word-of-mouth always helps :)

Thanks again,
Baptiste
