### ISSUE TITLE
Console output of strings can be confusing for beginners

### ISSUE THREAD

**Issue by vsemozhetbyt** [bpesquet/thejsway#73]
In the `chapter01.md`, there are screenshots of some console outputs, They show strings in quotes, but `console.log()` produces string output without quotes (at least in the last Chrome, Firefox, and Node.js). Could it cause some confusing for beginners?

**Comment by vsemozhetbyt** [comment]
Chrome:

![c](https://user-images.githubusercontent.com/10393198/28800901-b37f0336-7657-11e7-8786-7de85ebd0b20.png)

Firefox:

![f](https://user-images.githubusercontent.com/10393198/28800902-b398b128-7657-11e7-8989-7a432e3da3b7.png)

Node.js:

![n](https://user-images.githubusercontent.com/10393198/28800903-b3a65ff8-7657-11e7-9f9f-05e2e2af54dd.png)

**Comment by thangduong3010** [comment]
Have you seen output with quotes elsewhere?

From my iPhone with love

**Comment by vsemozhetbyt** [comment]
@thangduong3010 I cannot recall. Output with quotes may be prodused by a raw REPL evaluation, without `console.log()`:
```js
> "Hello from JavaScript!"
"Hello from JavaScript!"
> "Let's do some math"
"Let's do some math" 
```

**Comment by thangduong3010** [comment]
I don't think there is confusion here. The way console.log() work differs
from the way REPL evaluate. You can get the same result when you type "Hello
from JavaScript!" into a browser

**Comment by vsemozhetbyt** [comment]
@thangduong3010 I mean if readers run the code fragments with `console.log()` in the Chrome or Firefox and get the output without quotes and then compare it with the screenshots, they may be confused.

**Comment by hosam1696** [comment]
@vsemozhetbyt as in the figures in chapter one [codepen console](https://codepen.io/pen/?editors=1111) is used instead of browser console, that indicates it's type by putting it surrounding by quotes i think it will not be confusing that much but not hurt if there is hint for that.
