### ISSUE TITLE
chapter02.md: some vagueness

### ISSUE THREAD

**Issue by vsemozhetbyt** [bpesquet/thejsway#74]
> For number variables, the operators `+=` and `++` can **increment** (increase by 1) their value.

`+=` can increase more than by 1 (`a += 2`).

> You can also increase or decrease a value of a number with `+=` and `++`.

Should the `-=` and `--` be mentioned to match "decrease"?

> In JavaScript and many other programming languages, a **code block** is a portion of a program delimited by a pair of opening and closing braces. By default, a JavaScript program forms one block of code.
>

> ```js
> let nb1 = 0;
> {
>   nb1 = 1; // OK : nb1 is declared in the parent block
>   const nb2 = 0;
> }
> console.log(nb1); // OK : nb1 is declared in the current block
> console.log(nb2); // Error! nb2 is not visible here
> ```

1. Maybe it is worth to be noted that a file can produce a code block (scope) without braces (otherwise "parent block" can be confusing for beginners here).

2. I may be wrong, but `nb` abbreviation is not common for "number" in English (compare: https://fr.wikipedia.org/wiki/NB vs https://en.wikipedia.org/wiki/NB). Maybe `num` is more usual (if you decide to replace, do not forget places like [this](https://github.com/bpesquet/thejsway/blob/master/manuscript/appendix02.md#choose-meaningful-names))

**Comment by vsemozhetbyt** [comment]
> If a number fails to convert, you'll get the result `NaN` (_Not a Number_).

Maybe 'If a value fails to convert into a number...'?

**Comment by vsemozhetbyt** [comment]
![Execution result](https://raw.githubusercontent.com/bpesquet/thejsway/master/manuscript/images/chapter02-04.png)
![Execution result](https://raw.githubusercontent.com/bpesquet/thejsway/master/manuscript/images/chapter02-05.png)
Maybe these screenshots can be taken from a browser with English interface?

**Comment by mtrivera** [comment]
I submitted a PR for the chap02 screenshots. If anyone wants to tackle chap11, see #104 .
