### ISSUE TITLE
Correct typo in charter 18 

### ISSUE THREAD

**Issue by phucthaidoan** [bpesquet/thejsway#77]
- Typo:

Section: https://github.com/bpesquet/thejsway/blob/master/manuscript/chapter18.md#kick-off-a-repeated-action

_which can bu used to further modify it_ => which can be used to further modify it

- Code:
Section: https://github.com/bpesquet/thejsway/blob/master/manuscript/chapter18.md#animate-page-elements

`// Move the block to the left
const moveBlock = () => {
  // Convert the left position of the block (value of the form "XXpx") to a number
  const xBlock = parseFloat(getComputedStyle(**blockElement** ).left);
  // Move the block to the right
  **blockElement** .style.left = (xBlock + movement) + "px";
  // Have the browser call moveBlock as soon as possible
  requestAnimationFrame(moveBlock);
};

const frameElement = document.getElementById("frame");
const blockElement = document.getElementById("block");

// Movement value in pixels
const movement = 7;

// Start the animation
requestAnimationFrame(moveBlock);`

Thanks,
Phuc Thai

**Comment by bpesquet** [comment]
Thanks for your help. Would you mind creating a pull request to correct these mistakes?

**Comment by phucthaidoan** [comment]
Sorry for my late response. It seems that they are corrected.
