### ISSUE TITLE
Error on Chapter 14

### ISSUE THREAD

**Issue by ivq** [bpesquet/thejsway#85]
> `// Get all h2 elements into an array
const titleElements = document.getElementsByTagName("h2");
console.log(titleElements[0]);     // Show the first h2
console.log(titleElements.length); // 2 (total number of h2 elements in the page)`

There should be **3** h2 elements. And the corresponding [picture14-07](https://github.com/bpesquet/thejsway/blob/master/manuscript/images/chapter14-07.png) is not correct.

[Picture14-01](https://github.com/bpesquet/thejsway/blob/master/manuscript/images/chapter14-01.png) and [picture14-02](https://github.com/bpesquet/thejsway/raw/master/manuscript/images/chapter14-02.png) lack a few lines of code.

**Comment by bpesquet** [comment]
Thanks for pointing this out.
