### ISSUE TITLE
An ambiguity in the chapter04.md

### ISSUE THREAD

**Issue by vsemozhetbyt** [bpesquet/thejsway#89]
> Improve the program so that it also shows odd numbers. Improve it again so that the initial number is given by the user.
> 
> > This program must show exactly 10 numbers including the first one, not 11 numbers!

If the initial number is given by the user, could this program show less than 10 numbers?

**Comment by bpesquet** [comment]
No, it should always display 10 numbers.

**Comment by vsemozhetbyt** [comment]
@bpesquet Sorry, I cannot understand. If a user sets the initial number as `9`, how this program can output `10` odd/even numbers between `9` and `10`?

**Comment by bpesquet** [comment]
OK, the sentence is hopefully more clear now.

**Comment by vsemozhetbyt** [comment]
@bpesquet 
This is the second possible variant:
```js
for (let i = 1; i <= 10; i++) {
  if (i % 2 === 0) {
    console.log(`${i} is even`);
  } else {
    console.log(`${i} is odd`);
  }
}
```
output:
```console
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even
```
This is the third possible variant with a user input:
```js
for (let i = Number(prompt("Type the initial number:")); i <= 10; i++) {
  if (i % 2 === 0) {
    console.log(`${i} is even`);
  } else {
    console.log(`${i} is odd`);
  }
}
```
Output if a user types `9`:
```console
9 is odd
10 is even
```
As you can see, the last program cannot always show exactly 10 numbers.
