### ISSUE TITLE
chapter07.md: is there a reason why .shift() is not mentioned?

### ISSUE THREAD

**Issue by vsemozhetbyt** [bpesquet/thejsway#96]
It seems to be a simple and useful method, easier than `.splice()` for the first element removing, and somehow lacking for complete symmetry with `.push()`, `.unshift()` and `.pop()`.

**Comment by bpesquet** [comment]
No real reason, this chapter evolved to meet the needs of other parts of the book. Presenting too many methods could become confusing for the reader, but `shift()` is a good candidate.

Thanks for the idea!
